package ufps.poo.formulauno.gui;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import ufps.poo.formulauno.negocio.Formula1;

public class PilotoPanel extends javax.swing.JPanel {

    private Formula1 form1;

    /**
     * Creates new form EscuderiaPanel
     */
    public PilotoPanel(Formula1 form1) {
        initComponents();
        this.form1 = form1;
        
        String nombre[] = this.form1.concatenarNombreEscuderia().split("-");
        for(String x: nombre)
            this.cmbEscuderiaPerteneciente.addItem(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPeriodoContrato = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombrePiloto = new javax.swing.JTextField();
        txtAñoNacimiento = new javax.swing.JTextField();
        rbPeriodoContrato1_3 = new javax.swing.JRadioButton();
        rbPeriodoContrato4_6 = new javax.swing.JRadioButton();
        rbPeriodoContrato7_10 = new javax.swing.JRadioButton();
        cmbEscuderiaPerteneciente = new javax.swing.JComboBox();
        chkbAñoCampeon_2011 = new javax.swing.JCheckBox();
        chkbAñoCampeon_2012 = new javax.swing.JCheckBox();
        chkbAñoCampeon_2013 = new javax.swing.JCheckBox();
        chkbAñoCampeon_2014 = new javax.swing.JCheckBox();
        txtAñoIngreso = new javax.swing.JTextField();
        cmbPaisOrigen = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Registrar Piloto a Escuderia");

        jLabel2.setText("Ingrese la informacion del piloto");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre: ");

        jLabel4.setText("Año de ingreso: ");

        jLabel5.setText("Años campeón: ");

        jLabel6.setText("País de origen: ");

        jLabel7.setText("Año de nacimiento: ");

        jLabel8.setText("Periodo de contrato: ");

        jLabel9.setText("Escudería: ");

        bgPeriodoContrato.add(rbPeriodoContrato1_3);
        rbPeriodoContrato1_3.setText("1-3");

        bgPeriodoContrato.add(rbPeriodoContrato4_6);
        rbPeriodoContrato4_6.setText("4-6");

        bgPeriodoContrato.add(rbPeriodoContrato7_10);
        rbPeriodoContrato7_10.setText("7-10");

        chkbAñoCampeon_2011.setText("2011");

        chkbAñoCampeon_2012.setText("2012");

        chkbAñoCampeon_2013.setText("2013");

        chkbAñoCampeon_2014.setText("2014");

        cmbPaisOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colombia", "Argentina", "Ecuador" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(layout.createSequentialGroup()
                                .add(btnLimpiar)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnRegistrar))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(layout.createSequentialGroup()
                                        .add(rbPeriodoContrato1_3)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(rbPeriodoContrato4_6)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(rbPeriodoContrato7_10))
                                    .add(txtAñoNacimiento)
                                    .add(txtNombrePiloto)
                                    .add(cmbEscuderiaPerteneciente, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(layout.createSequentialGroup()
                                        .add(chkbAñoCampeon_2011)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(chkbAñoCampeon_2012))
                                    .add(layout.createSequentialGroup()
                                        .add(chkbAñoCampeon_2013)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(chkbAñoCampeon_2014))
                                    .add(txtAñoIngreso)
                                    .add(cmbPaisOrigen, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .add(0, 14, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtNombrePiloto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(cmbPaisOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(txtAñoNacimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(rbPeriodoContrato1_3)
                    .add(rbPeriodoContrato4_6)
                    .add(rbPeriodoContrato7_10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(cmbEscuderiaPerteneciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txtAñoIngreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(chkbAñoCampeon_2011)
                    .add(chkbAñoCampeon_2012))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chkbAñoCampeon_2013)
                    .add(chkbAñoCampeon_2014))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnRegistrar)
                    .add(btnLimpiar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // Se hace captura de los datos
        // Se hacen validaciones de contenido
        // Se invoca el metodo del negocio
        //boolean exito = form1.agregarPiloto(Atributos...);

        String nombre = this.txtNombrePiloto.getText();
        String pais = this.cmbPaisOrigen.getSelectedItem().toString();
        String añoNacimiento = this.txtAñoNacimiento.getText();
        String periodoContrato = this.obtenerTexto(bgPeriodoContrato);
        String escuderia = this.cmbEscuderiaPerteneciente.getSelectedItem().toString();
        String añoIngreso = this.txtAñoIngreso.getText();
        String[] añoCampeon = this.obtenerCheck().split("-");

        if (nombre.isEmpty() || añoNacimiento.isEmpty() || añoIngreso.isEmpty()) {
            Ventana.imp("Debe ingresar todos los datos", "Sistema");
            return;
        }

        if (!isNumeric(añoNacimiento) || !isNumeric(añoIngreso)) {
            Ventana.imp("Ingrese valores numericos a los campos correspondientes", "Sistema");
        }

        String mensaje = this.form1.agregarPiloto(nombre, pais, Integer.parseInt(añoNacimiento), periodoContrato, añoCampeon, Integer.parseInt(añoIngreso), escuderia);
        Ventana.imp(mensaje, "Sistema");
        
        this.limpiarCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private String obtenerTexto(ButtonGroup bg) {
        String valor = "";

        Enumeration<AbstractButton> radios = bg.getElements();
        while (radios.hasMoreElements()) {
            JRadioButton temp = (JRadioButton) radios.nextElement();
            if (temp.isSelected()) {
                valor = temp.getText();
            }
        }

        return valor;
    }
    
    private void limpiarCampos(){
        this.txtNombrePiloto.setText("");
        this.txtAñoNacimiento.setText("");
        this.txtAñoIngreso.setText("");
        this.cmbPaisOrigen.setSelectedIndex(0);
        this.cmbEscuderiaPerteneciente.setSelectedIndex(0);
        this.bgPeriodoContrato.clearSelection();
        this.chkbAñoCampeon_2011.setSelected(false);
        this.chkbAñoCampeon_2012.setSelected(false);
        this.chkbAñoCampeon_2013.setSelected(false);
        this.chkbAñoCampeon_2014.setSelected(false);
    }

    private String obtenerCheck() {
        String valor = "";

        if (this.chkbAñoCampeon_2011.isSelected()) {
            valor += this.chkbAñoCampeon_2011.getText() + "-";
        }

        if (this.chkbAñoCampeon_2012.isSelected()) {
            valor += this.chkbAñoCampeon_2012.getText() + "-";
        }

        if (this.chkbAñoCampeon_2013.isSelected()) {
            valor += this.chkbAñoCampeon_2013.getText() + "-";
        }

        if (this.chkbAñoCampeon_2014.isSelected()) {
            valor += this.chkbAñoCampeon_2014.getText() + "-";
        }

        return valor;
    }

    private static boolean isNumeric(String num) {
        try {
            int d = Integer.parseInt(num);
        } catch (NumberFormatException nfe) {
            System.out.println(""+nfe);
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPeriodoContrato;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkbAñoCampeon_2011;
    private javax.swing.JCheckBox chkbAñoCampeon_2012;
    private javax.swing.JCheckBox chkbAñoCampeon_2013;
    private javax.swing.JCheckBox chkbAñoCampeon_2014;
    private javax.swing.JComboBox cmbEscuderiaPerteneciente;
    private javax.swing.JComboBox cmbPaisOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbPeriodoContrato1_3;
    private javax.swing.JRadioButton rbPeriodoContrato4_6;
    private javax.swing.JRadioButton rbPeriodoContrato7_10;
    private javax.swing.JTextField txtAñoIngreso;
    private javax.swing.JTextField txtAñoNacimiento;
    private javax.swing.JTextField txtNombrePiloto;
    // End of variables declaration//GEN-END:variables
}
